MusicFolder = "/12TB-HDD/Navidrome/Music"
DataFolder = "/12TB-HDD/Navidrome/Data"
CoverArtPriority = "front.*, embedded"
CoverJpegQuality = 100
Deezer.Enabled = true
Deezer.Language = "en"
DefaultDownsamplingFormat = "opus"
DefaultLanguage = "en"
DefaultTheme = "Dark"
DefaultUIVolume = 100
EnableArtWorkPrecache = true
EnableCoverAnimation = true
EnableDownloads = true
EnableExternalServices = true
EnableFavourites = true
EnableGravatar = false
ImageCacheSize = "500MB"
Scanner.Enabled = true
Scanner.Schedule = "@every 24h"
